gcp:
  project_id: "mystic-pact-455314-g4"
  credentials_path: "~/.gcp/gcs-user-key.json"

storage:
  bucket: "jaffle-files"
  raw_prefix: "raw"

bigquery:
  dataset_id: "jaffle_raw"

tables:
  raw_orders:
    path: "raw/raw_orders.csv"
    schema:
      - name: id
        field_type: STRING
        mode: REQUIRED
      - name: customer
        field_type: STRING
        mode: REQUIRED
      - name: ordered_at
        field_type: DATETIME
        mode: REQUIRED
      - name: store_id
        field_type: STRING
        mode: REQUIRED
      - name: subtotal
        field_type: INTEGER
        mode: REQUIRED
      - name: tax_paid
        field_type: INTEGER
        mode: REQUIRED
      - name: order_total
        field_type: INTEGER
        mode: REQUIRED
    partition_field: ordered_at

  raw_items:
    path: "raw/raw_items.csv"
    schema:
      - name: id
        field_type: STRING
        mode: REQUIRED
      - name: order_id
        field_type: STRING
        mode: REQUIRED
      - name: sku
        field_type: STRING
        mode: REQUIRED

  raw_products:
    path: "raw/raw_products.csv"
    schema:
      - name: sku
        field_type: STRING
        mode: REQUIRED
      - name: name
        field_type: STRING
        mode: REQUIRED
      - name: field_type
        field_type: STRING
        mode: NULLABLE
      - name: price
        field_type: INTEGER
        mode: REQUIRED
      - name: description
        field_type: STRING
        mode: NULLABLE

  raw_stores:
    path: "raw/raw_stores.csv"
    schema:
      - name: id
        field_type: STRING
        mode: REQUIRED
      - name: name
        field_type: STRING
        mode: REQUIRED
      - name: opened_at
        field_type: DATETIME
        mode: REQUIRED
      - name: tax_rate
        field_type: FLOAT
        mode: REQUIRED

  raw_customers:
    path: "raw/raw_customers.csv"
    schema:
      - name: id
        field_type: STRING
        mode: REQUIRED
      - name: name
        field_type: STRING
        mode: REQUIRED

  raw_tweets:
    path: "raw/raw_tweets.csv"
    schema:
      - name: id
        field_type: STRING
        mode: REQUIRED
      - name: user_id
        field_type: STRING
        mode: REQUIRED
      - name: tweeted_at
        field_type: DATETIME
        mode: REQUIRED
      - name: content
        field_type: STRING
        mode: REQUIRED

  raw_supplies:
    path: "raw/raw_supplies.csv"
    schema:
      - name: id
        field_type: STRING
        mode: REQUIRED
      - name: name
        field_type: STRING
        mode: REQUIRED
      - name: cost
        field_type: INTEGER
        mode: REQUIRED
      - name: perishable
        field_type: BOOL
        mode: REQUIRED
      - name: sku
        field_type: STRING
        mode: REQUIRED
      

